version: "3"

services:
  web:
    build: ./docker/web
    container_name: web
    environment:
      - CHOKIDAR_USEPOLLING=true
      - TZ=${TZ}
    networks:
      - nuxt-laravel-app-net
    tty: true
    volumes:
      - ./nuxt-app:/var/www/nuxt-app
    working_dir: /var/www/nuxt-app
    restart: always

  api:
    build: ./docker/api
    container_name: api
    environment:
      - TZ=${TZ}
    networks:
      - nuxt-laravel-app-net
    volumes:
      - ./laravel-app:/var/www/laravel-app
    working_dir: /var/www/laravel-app
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    environment:
      - TZ=${TZ}
    networks:
      - nuxt-laravel-app-net
    ports:
      - ${WEB_PORT}:80
      - ${API_PORT}:8000
    volumes:
      - ./laravel-app:/var/www/laravel-app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx
    restart: always

  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: MySQL
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
    networks:
      - nuxt-laravel-app-net
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/logs:/var/log/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin
    container_name: phpMyAdmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - nuxt-laravel-app-net
    ports:
      - ${PMA_PORT}:80
    depends_on:
      - db
    restart: always

networks:
  nuxt-laravel-app-net:
